did a basic makefile and some tests there and there, I really need to push more often during that project.

diff --git a/srcs/requirements/nginx/Dockerfile b/srcs/requirements/nginx/Dockerfile
--- a/srcs/requirements/nginx/Dockerfile
+++ b/srcs/requirements/nginx/Dockerfile
@@ -1,22 +1,51 @@
-FROM debian:bookworm
+#pas la derniere avant derniere
+FROM debian:bookworm 
 
-RUN apt -y update && \
-apt install -y nginx
+LABEL ldevoude="ldevoude@student.42lyon.fr"
+LABEL version="1.0"
+LABEL description="nginx docker"
 
-RUN apt install vim -y    
-RUN apt install curl -y
+# CMD ["echo", "Hello, Sunshine!"]
 
-RUN mkdir -p /etc/nginx/ssl
-RUN apt install openssl -y
+#rm folder that contain apt logs
+RUN apt-get -y update && \
+apt-get install -y bash && \
+apt install -y curl nginx vim openssl && \
+apt clean && \
+rm -rf /var/lib/apt/lists/* && \
+mkdir -p /etc/nginx/ssl && \
+openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=ARA/L=Charboville/O=42/OU=42/CN=ldevoude.42.fr/UID=ldevoude" && \
+mkdir -p /var/run/nginx
 
-RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/c=FR/ST=ARA/L=Lyon/O=42/OU=42/CN=ldevoude.42.fr/UID=ldevoude"
-
-RUN mkdir -p /var/run/nginx
-
+#COPY tools/index.html /usr/share/nginx/html/index.html
 COPY conf/nginx.conf /etc/nginx/nginx.conf
 
-RUN chmod 755 /var/www/html
-RUN chown -R www-data:www-data /var/www/html
+# ENV USER=ldevoude
+# ENV shell=/bin/bash
 
-CMD [ "nginx", "-g", "daemon off;" ]
+#MariaDB default port
+#sert a rien ici mettre dans docker-compose.yml
+# EXPOSE 443:443
+# EXPOSE 80
 
+RUN chmod 777 /var/www/html && \
+    chown -R www-data:www-data /var/www/html
+
+
+#run to check if container is healthy, if 0 healthcheck is a success, 1 it fails
+#mettre dans docker-compose?
+# HEALTHCHECK --start-period=5m \
+#   CMD mariadb -e 'SELECT @@datadir;' || exit 1
+
+#entry point = pour finir execute ce script
+# cmd = pour finir execute cette commande
+CMD ["nginx", "-g", "daemon off;"]
+
+#todebug?
+#CMD sleep infinity
+#utiliser sh plutot que bash
+
+
+
+
+#entrypoint
